# Generated by Django 3.1.2 on 2020-12-19 18:22

from django.db import migrations, models
from django.db.migrations.operations.models import DeleteModel
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administratif',
            fields=[
                ('Prenom', models.CharField(max_length=30)),
                ('Nom', models.CharField(max_length=30)),
                ('Adressemail', models.EmailField(max_length=60)),
                ('Naiss', models.DateField(auto_now_add=True)),
                ('Numadministratif', models.IntegerField(primary_key=True, serialize=False)),
                ('Statut', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ), 
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('Prenom', models.CharField(max_length=30)),
                ('Nom', models.CharField(max_length=30)),
                ('Adressemail', models.EmailField(max_length=60)),
                ('Naiss', models.DateField(auto_now_add=True)),
                ('NumEtudiant', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('idFormation', models.IntegerField(primary_key=True, serialize=False)),
                ('NomFormation', models.CharField(max_length=100)),
                ('UFRRattachement', models.CharField(default='Segmi', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('idgroupe', models.IntegerField(primary_key=True, serialize=False)),
                ('Libelle', models.CharField(max_length=100)),
                ('idniveau', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('Prenom', models.CharField(max_length=30)),
                ('Nom', models.CharField(max_length=30)),
                ('Adressemail', models.EmailField(max_length=60)),
                ('Naiss', models.DateField(auto_now_add=True)),
                ('NumPersonnel', models.IntegerField(primary_key=True, serialize=False)),
                ('Statut', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('Prenom', models.CharField(max_length=30)),
                ('Nom', models.CharField(max_length=30)),
                ('Adressemail', models.EmailField(max_length=60)),
                ('Naiss', models.DateField(auto_now_add=True)),
                ('NumProfesseur', models.IntegerField(primary_key=True, serialize=False)),
                ('Statut', models.CharField(max_length=30)),
                ('Experience', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('Nom', models.IntegerField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=100)),
                ('Batiment', models.CharField(max_length=100)),
                ('Capacite', models.IntegerField()),
                ('NbPC', models.IntegerField()),
                ('Projecteur', models.IntegerField()),
                ('Tableaux', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomMatière', models.CharField(max_length=30)),
                ('ECTS', models.IntegerField()),
                ('Type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('NumSemestre', models.IntegerField(primary_key=True, serialize=False)),
                ('DateDebut', models.DateTimeField(auto_now_add=True)),
                ('NbSemaines', models.IntegerField()),
                ('fk_Formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionEDT.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('IdSeance', models.IntegerField(primary_key=True, serialize=False)),
                ('TimecodeDebut', models.DateTimeField(auto_now_add=True)),
                ('TimecodeFIN', models.DateTimeField(auto_now_add=True)),
                ('fk_Salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionEDT.salle')),
                ('fk_UE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionEDT.uniteenseignement')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolPresence', models.BooleanField(default=False)),
                ('fk_Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionEDT.etudiant')),
                ('fk_Seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionEDT.seance')),
            ],
        ),
    ]
